project:
  type: website

website:
  title: "Versionning et Repository (xin206 - xdev206)"
  back-to-top-navigation: true
  sidebar:
    search: true
    style: "docked"
    contents:
      - text: "Accueil"
        href: index.qmd 
      - section: "Cours"
        contents:
          - cours1.qmd
          - cours2.qmd
          - cours3.qmd
          - cours4.qmd
      - section: "TPs"
        contents:
          - tp1.qmd
          - tp2.qmd
          - tp3.qmd
          - tp4.qmd
  
  navbar:
    right:
      - href: index.qmd
      - text: Cours
        menu:
          - href: cours1.qmd
          - href: cours2.qmd
          - href: cours3.qmd
          - href: cours4.qmd
      - text: TPs
        menu: 
          - href: tp1.qmd
          - href: tp2.qmd
          - href: tp3.qmd
          - href: tp4.qmd
  favicon: assets/favicon.png

format:
  html:
    page-layout: full
    theme: cosmo
    highlight:
      style: github
    linestretch: 1.7
    toc: true
    toc-title: Contenu